### ISSUE TITLE
SQLite3

### ISSUE THREAD

**Issue by tburd** [tschoffelen/db.php#10]
Is it possible to use SQLite3 instead of MySQL?

$db = new SQLite3('test.db');

Fatal error: Uncaught Error: Call to undefined method SQLite3::select() in teste.php:5 Stack trace: #0 {main} thrown in test.php on line 5

Thank you very much!
Best regards

**Comment by tschoffelen** [comment]
This library currently heavily relies on the MySQLi extension and functions, so it would take quite a big rewrite to make this work for SQLite.
