### ISSUE TITLE
Fatal Error with long queries ?

### ISSUE THREAD

**Issue by PierreG89** [tschoffelen/db.php#11]
Not confirmed 100% that it is not an error by my side but, here is what I have:

Fatal error: Uncaught DatabaseException: Database error: MySQL server has gone away in /home/xxx/Database.php:79 Stack trace: #0 /home/xxx/Database.php(490): Database->_error('MySQL server ha...') #1 /home/xxx/mycode.php(275): Database->update('mytable', Array, Array) #2 {main} thrown in /home/xxx/Database.php on line 79

EVERYTIME I try to update it within PHP code with this library, BUT when I try the same query (the query echo'ed on line 386 of Database.php) directly in phpMyAdmin, it works.

Here is what it's like for info.:

UPDATE `mytable` SET `idz`='2951;1325;1104;1364;4025;1335;460;4169;6052;6053;339;3579;3580;3577;3610;3611;3582;4076;5272;1342;1321;1361;1331;1360;1332;1358;1349;2053;1359;3597;2142;3595;4075;720;3142;5422;2289;3600;4079;2636;2619;2622;2635;3911;3823;4088;4093;4084;4081;119;5425;486;3571;3609;3592;1347;4618;4621;4617;4607;3809;5682;3617;802;808;178;177;174;1196;1186;175;176;2375;2381;2378;2372;2377;2379;1003;1026;872;909;4115;4111;4113;4109;4119;3589;3603;3588;3607;3925;336;1362;1354;1345;1344;1328;1339;1329;1340;1183;5169;3690;462;457;464;1115;109;5319', `idz_dates`='2018-11-13 22:35:13;2018-11-13 22:35:13;2018-11-13 22:35:14;2018-11-13 22:35:14;2018-11-13 22:35:14;2018-11-13 22:35:15;2018-11-13 22:35:15;2018-11-13 22:35:16;2018-11-13 22:35:16;2018-11-13 22:35:17;2018-11-13 22:35:17;2018-11-13 22:35:18;2018-11-13 22:35:18;2018-11-13 22:35:19;2018-11-13 22:35:19;2018-11-13 22:35:19;2018-11-13 22:35:20;2018-11-13 22:35:20;2018-11-13 22:35:21;2018-11-13 22:35:21;2018-11-13 22:35:22;2018-11-13 22:35:22;2018-11-13 22:35:23;2018-11-13 22:35:24;2018-11-13 22:35:24;2018-11-13 22:35:25;2018-11-13 22:35:25;2018-11-13 22:35:26;2018-11-13 22:35:26;2018-11-13 22:35:27;2018-11-13 22:35:27;2018-11-13 22:35:28;2018-11-13 22:35:29;2018-11-13 22:35:29;2018-11-13 22:35:30;2018-11-13 22:35:31;2018-11-13 22:35:31;2018-11-13 22:35:31;2018-11-13 22:35:31;2018-11-13 22:35:32;2018-11-13 22:35:32;2018-11-13 22:35:32;2018-11-13 22:35:33;2018-11-13 22:35:33;2018-11-13 22:35:33;2018-11-13 22:35:33;2018-11-13 22:35:34;2018-11-13 22:35:34;2018-11-13 22:35:35;2018-11-13 22:35:35;2018-11-13 22:35:36;2018-11-13 22:35:36;2018-11-13 22:35:36;2018-11-13 22:35:36;2018-11-13 22:35:37;2018-11-13 22:35:37;2018-11-13 22:35:38;2018-11-13 22:35:38;2018-11-13 22:35:38;2018-11-13 22:35:39;2018-11-13 22:35:39;2018-11-13 22:35:39;2018-11-13 22:35:40;2018-11-13 22:35:41;2018-11-13 22:35:41;2018-11-13 22:35:41;2018-11-13 22:35:42;2018-11-13 22:35:42;2018-11-13 22:35:43;2018-11-13 22:35:43;2018-11-13 22:35:43;2018-11-13 22:35:43;2018-11-13 22:35:44;2018-11-13 22:35:45;2018-11-13 22:35:45;2018-11-13 22:35:46;2018-11-13 22:35:46;2018-11-13 22:35:46;2018-11-13 22:35:47;2018-11-13 22:35:47;2018-11-13 22:35:48;2018-11-13 22:35:48;2018-11-13 22:35:49;2018-11-13 22:35:49;2018-11-13 22:35:49;2018-11-13 22:35:49;2018-11-13 22:35:50;2018-11-13 22:35:51;2018-11-13 22:35:51;2018-11-13 22:35:51;2018-11-13 22:35:51;2018-11-13 22:35:52;2018-11-13 22:35:52;2018-11-13 22:35:52;2018-11-13 22:35:52;2018-11-13 22:35:53;2018-11-13 22:35:53;2018-11-13 22:35:53;2018-11-13 22:35:53;2018-11-13 22:35:54;2018-11-13 22:35:54;2018-11-13 22:35:54;2018-11-13 22:35:54;2018-11-13 22:35:55;2018-11-13 22:35:55;2018-11-13 22:35:55;2018-11-13 22:35:56;2018-11-13 22:35:56;2018-11-13 22:35:57;2018-11-13 22:35:57', `idz_links`='0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0', `idz_prices`='0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0;0', `idz_quantities`='1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1;1' WHERE `some_condition`='is_like_this'

generated by 

$db->update('mytable', ['idz' => implode(";", $idz_array), 'idz_dates' => implode(";", $dates_array), 'idz_links' => implode(";", $links_array), 'idz_prices' => implode(";", $prices_array), 'idz_quantities' => implode(";", $quantities_array)], ["some_condition" => $is_like_this]);

**Comment by tschoffelen** [comment]
Hmm, interesting.

Could you try the suggestions on this page first to make sure it doesn't have anything to do with your MySQL server?

https://matomo.org/faq/troubleshooting/faq_183/

**Comment by PierreG89** [comment]
I read your advice, thanks. But I was trying to search how to verify the value of these variables (wait_timeout , max_allowed_packet...) because, as for now, my project is still a " project " and it is on a shared hosting. I can't access all that I want, but since now, as shared ressources seemed decent, it has not been a problem. I asked the hosting support but I am not satisfied with the answers (...).

I now have 2 solutions: digging more by the side of my hosting and/or ask if you may try the update by your side to see if you have the same result. I do not want to take your time so in any case, I will search more by my side. Thanks.

**Comment by tschoffelen** [comment]
I just tried it in a few different environments, but the only error I get is about the table not existing, not the `MySQL server has gone away` error unfortunately...

**Comment by PierreG89** [comment]
Thanks a lot. I'm still investigating. I will try another hoster asap to confirm it. If a server parameter is wrong, I have to know which as it can be helpful ton include it in doc

**Comment by PierreG89** [comment]
Here is my feedback. Long queries doesn't work as expected if wait_timeout is too short. It was 30 on mine and the query of this issue was usually more than 37 seconds... It has been adapted to 60 and now it works great. I can't do this by myself, I had to prove to my hoster that something was wrong: I tried via cron, ssh,... even ANOTHER hoster. It was working great on another hoster so I suppose wait_timeout was bigger. Really GOOD to know that this parameter must be sufficient in order to have great experience with your project or that queries need to be devided if parameter can't be ajusted...

**Comment by tschoffelen** [comment]
Wow, seems like you went to a ton of work to figure this out, awesome!

 Closing this issue for now, feel free to submit a PR to add this notice to the README.md.
