### ISSUE TITLE
Where between is not working

### ISSUE THREAD

**Issue by matthieugluszkowski** [tschoffelen/db.php#13]
Hello,
I would like to do this request, but it's not working, could you help me?

$db->select($table, [
				'latitude' => 'Between "48.864690367882"',
				'latitude' => '"48.900663232118"'
			], false, false)->result();

The request SQL is : SELECT * FROM table WHERE latitude Between "48.864690367882" And "48.900663232118" And longitude Between "2.2993563961954" And "2.3540594038046"

Thank you in advance

**Comment by tschoffelen** [comment]
The only way to do that currently is the following:

```
$db->select($table, [
'latitude BETWEEN "48.864690367882" AND "48.900663232118"'
], false, false)->result();
```
