### ISSUE TITLE
charset issue

### ISSUE THREAD

**Issue by mrqaidi** [tschoffelen/db.php#4]
Hi
 thanks for this nice class   its useful  but there is  one problem with it  there  and you can fix it by adding  set_charset to utf8

add this line 
`$this->mysql->set_charset("utf8");
`
after 
`$this->mysql = mysqli_connect($host, $username, $password, $database_name);`

**Comment by tschoffelen** [comment]
Thanks! Feel free to open a pull request to incorporate that change into the library!
