### ISSUE TITLE
unable to set NULL

### ISSUE THREAD

**Issue by PierreG89** [tschoffelen/db.php#7]
Hi,

Can't update something to NULL.
By my side, updating int put 0 into it and updating string puts '' (nothing) but not NULL (that is the default value, it can be null).

so 

$db->update('myTable', array('Name' => NULL, 'Number' => NULL ... makes '' into Name and 0 into Number

is there a way to set Null or this really is an issue?

Plus I think readme has still little error:

_$db->row_array() returns the first row that matches the query as an object (stdClass)_

**Comment by tschoffelen** [comment]
Oh, good point, I recently fixed this in a version of this library that we're using internally.

Will see if I can merge it upstream.

**Comment by MircoCagni** [comment]
I have the same problem when try to update data at 0/1 (in sql is bit(1) camp) did you find any solution?
